name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:devrel-ci

      - name: Echo on tailnode
        run: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.VPS_USER }}@thor "
            echo "Hello world !"
          "                  

