name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:devrel-ci

      - name: Create app directory 
        run: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p ${{ secrets.VPS_APP_PATH }}"        

      - name: Copy
        run: |
          scp -r * ${{ secrets.VPS_USER }}@{{ secrets.VPS_HOST }}:${{ secrets.VPS_APP_PATH }}    

      - name: Ansible Galaxy update
        run: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.VPS_USER }}@{{ secrets.VPS_HOST }} "
          cd ${{ secrets.VPS_APP_PATH }}
          ansible-galaxy install -r requirements.yml
          "    

      - name: Execute ansible build
        run: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.VPS_USER }}@{{ secrets.VPS_HOST }} "
          cd ${{ secrets.VPS_APP_PATH }}
          ansible-playbook -b deploy.yml -e '{"docker_compose_generator_output_path": "${{ secrets.VPS_APP_PATH }}", "appdata_path_server": "${{ secrets.VPS_APPDATA_PATH }}", } '
          "

      - name: Deploy
        run: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.VPS_USER }}@{{ secrets.VPS_HOST }} "
            cd ${{ secrets.VPS_APP_PATH }}
            docker compose -f ${{ secrets.VPS_APP_PATH }}/compose.yaml pull
            docker compose -f ${{ secrets.VPS_APP_PATH }}/compose.yaml up -d 
          "               
      - name: Execute ansible build
        run: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.VPS_USER }}@{{ secrets.VPS_HOST }} "
          rm -rf ${{ secrets.VPS_APP_PATH }}
          "